"""
Incidents Router — FR-06
GET /incidents
POST /incidents — Manual declaration
GET /incidents/{id}/action-plan
"""

from __future__ import annotations
import uuid
from datetime import datetime
from typing import Optional
from fastapi import APIRouter, Depends, Query, HTTPException
from pydantic import BaseModel

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
from shared.mongodb import incidents_col, audit_logs_col
from shared.auth import get_current_user, CurrentUser, require_operator
from shared.schemas.models import (
    APIResponse, PaginatedResponse, IncidentModel, IncidentSeverity,
    IncidentStatus, GeoPoint, IncidentTimeline
)

router = APIRouter()


class DeclareIncidentRequest(BaseModel):
    type: str
    severity: IncidentSeverity
    latitude: float
    longitude: float
    description: str
    affected_trains: list[str] = []
    affected_segments: list[str] = []


@router.get("", summary="List incidents with status and severity")
async def list_incidents(
    severity: Optional[IncidentSeverity] = Query(None),
    status: Optional[IncidentStatus] = Query(None),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
    user: CurrentUser = Depends(get_current_user),
):
    query: dict = {}
    if severity:
        query["severity"] = severity.value
    if status:
        query["status"] = status.value

    skip = (page - 1) * page_size
    cursor = incidents_col().find(query, {"_id": 0}).sort("createdAt", -1).skip(skip).limit(page_size)
    items = await cursor.to_list(length=page_size)
    total = await incidents_col().count_documents(query)
    return PaginatedResponse(data=items, total=total, page=page, page_size=page_size)


@router.post("", summary="Manually declare an incident (FR-06.1)", status_code=201)
async def declare_incident(
    body: DeclareIncidentRequest,
    user: CurrentUser = Depends(require_operator),
):
    """
    FR-06.1: Human operators can manually declare an incident.
    Every incident is auto-tagged with location, type, severity, timestamp, data sources.
    """
    now = datetime.utcnow()
    incident_id = f"INC-{uuid.uuid4().hex[:8].upper()}"

    incident = {
        "incidentId": incident_id,
        "type": body.type,
        "severity": body.severity.value,
        "location": {
            "type": "Point",
            "coordinates": [body.longitude, body.latitude]
        },
        "status": IncidentStatus.DETECTED.value,
        "affectedTrains": body.affected_trains,
        "affectedSegments": body.affected_segments,
        "actionPlan": None,  # CrisisCommand Agent generates within 60s
        "timeline": [
            {
                "timestamp": now.isoformat(),
                "event": f"Incident manually declared: {body.description}",
                "actor": user.user_id,
                "metadata": {},
            }
        ],
        "dataSources": ["manual_declaration"],
        "createdAt": now.isoformat(),
        "resolvedAt": None,
    }

    await incidents_col().insert_one(incident)

    # Audit log
    await audit_logs_col().insert_one({
        "userId": user.user_id,
        "action": "DECLARE_INCIDENT",
        "timestamp": now,
        "metadata": {"incidentId": incident_id, "type": body.type, "severity": body.severity.value},
    })

    incident.pop("_id", None)
    return APIResponse(data=incident, message=f"Incident {incident_id} declared. AI Action Plan generating...", code=201)


@router.get("/{incident_id}/action-plan", summary="Fetch AI-generated action plan")
async def get_action_plan(
    incident_id: str,
    user: CurrentUser = Depends(get_current_user),
):
    """FR-06.2: Fetch AI-generated action plan for an incident."""
    incident = await incidents_col().find_one(
        {"incidentId": incident_id}, {"_id": 0}
    )
    if not incident:
        raise HTTPException(status_code=404, detail="Incident not found")

    action_plan = incident.get("actionPlan")
    if not action_plan:
        return APIResponse(
            message="Action plan is being generated by CrisisCommand Agent (within 60 seconds).",
            data=None
        )
    return APIResponse(data=action_plan)


@router.patch("/{incident_id}/action-plan", summary="Edit action plan (versioned)")
async def edit_action_plan(
    incident_id: str,
    updates: dict,
    rationale: str = "",
    user: CurrentUser = Depends(require_operator),
):
    """
    FR-06.2: Action Plans versioned; every human edit logged with userId + rationale.
    """
    incident = await incidents_col().find_one({"incidentId": incident_id})
    if not incident:
        raise HTTPException(status_code=404, detail="Incident not found")

    now = datetime.utcnow()
    current_plan = incident.get("actionPlan", {})
    version_num = len(current_plan.get("versions", [])) + 1

    # Append version history entry
    version_entry = {
        "version": version_num,
        "editedBy": user.user_id,
        "editedAt": now.isoformat(),
        "rationale": rationale,
        "snapshot": {k: v for k, v in current_plan.items() if k != "versions"},
    }

    # Merge updates into current plan
    updated_plan = {**current_plan, **updates}
    updated_plan.setdefault("versions", []).append(version_entry)

    await incidents_col().update_one(
        {"incidentId": incident_id},
        {
            "$set": {
                "actionPlan": updated_plan,
                "status": IncidentStatus.ACTIVE.value,
            },
            "$push": {
                "timeline": {
                    "timestamp": now.isoformat(),
                    "event": f"Action plan edited (v{version_num}): {rationale}",
                    "actor": user.user_id,
                    "metadata": {"version": version_num},
                }
            }
        }
    )

    await audit_logs_col().insert_one({
        "userId": user.user_id,
        "action": "EDIT_ACTION_PLAN",
        "timestamp": now,
        "metadata": {"incidentId": incident_id, "version": version_num, "rationale": rationale},
    })

    return APIResponse(message=f"Action plan updated (version {version_num})")
